name: VM State Change

on:
  workflow_dispatch:
    inputs:
      STATE:
        required: true
        type: choice
        options:
          - NONE
          - START
          - STOP
          - RESTART
      user_email_address:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: env print
        run: |
          EMAILS=${{ vars.EMAIL }}
          IFS=',' read -ra emails <<< "$EMAILS"
          for email in "${emails[@]}"; do
            echo "Processing $email"
          done
      - name: login to ACR
        id: process_json
        run: |
          # Your JSON data
          EMAIL_ADDRESS=$(jq -r '.inputs.user_email_address' $GITHUB_EVENT_PATH)
          echo ::add-mask::$EMAIL_ADDRESS
          echo "::add-mask::${{ inputs.user_email_address }}"
          echo "${{ inputs.user_email_address }}"
          echo "$EMAIL_ADDRESS"
          json_data='{"name": "zs-oyo-temp-vm","privateIp": "10.73.100.4","resourceGroup": "Oyo-migration-RG"}'

          name=$(echo "$json_data" | jq -r '.name')
          privateIp=$(echo "$json_data" | jq -r '.privateIp')
          resourceGroup=$(echo "$json_data" | jq -r '.resourceGroup')
          
          echo "NAME=$name" >> $GITHUB_OUTPUT
          echo "PRIVATE_IP=$privateIp" >> $GITHUB_OUTPUT
          echo "RESOURCE_GROUP=$resourceGroup" >> $GITHUB_OUTPUT


      - run: |
          echo "$EMAIL_ADDRESS"
          echo "Name: ${{ steps.process_json.outputs.NAME }}"
          echo "Private IP: ${{ steps.process_json.outputs.PRIVATE_IP }}"
          echo "Resource Group: ${{ steps.process_json.outputs.RESOURCE_GROUP }}"





     
