name: VM State Change

on:
  workflow_dispatch:
    inputs:
      VM IP:
        required: true
        type: string
      STATE:
        required: true
        type: choice
        options:
          - NONE
          - START
          - STOP
          - RESTART

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login to ACR
        shell: bash
        run: |
          # Get the GitHub Email using the GitHub REST API
          GITHUB_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/user/emails" | jq -r '.[] | select(.primary == true) | .email')
          echo "GitHub Email: $GITHUB_EMAIL"

      - name: Use GitHub Email in the Workflow
        run: |
          # Use the GitHub Email in other steps of the workflow
          echo "The user's GitHub Email is: $GITHUB_EMAIL"
