name: VM State Change

on:
  workflow_dispatch:
    inputs:
      VM IP:
        required: true
        type: string
      STATE:
        required: true
        type: choice
        options:
          - NONE
          - START
          - STOP
          - RESTART

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login to ACR
        shell: bash
        run: |
          email=$GITHUB_ACTOR
          echo $email
      - name: get email
        run: |
          echo $ENV_VARIABLE
