name: VM State Change

on:
  workflow_dispatch:
    inputs:
      STATE:
        required: true
        type: choice
        options:
          - NONE
          - START
          - STOP
          - RESTART

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login to ACR
        id: process_json
        run: |
          # Your JSON data
          json_data='{"name": "zs-oyo-temp-vm","privateIp": "10.73.100.4","resourceGroup": "Oyo-migration-RG"}'

          name=$(echo "$json_data" | jq -r '.name')
          privateIp=$(echo "$json_data" | jq -r '.privateIp')
          resourceGroup=$(echo "$json_data" | jq -r '.resourceGroup')

          echo "Name: $name"
          echo "Private IP: $privateIp"
          echo "Resource Group: $resourceGroup"

        env:
          NAME: ${{ steps.process_json.outputs.name }}
          PRIVATE_IP: ${{ steps.process_json.outputs.privateIp }}
          RESOURCE_GROUP: ${{ steps.process_json.outputs.resourceGroup }}

      - run: |
          echo "Name: $NAME"
          echo "Private IP: $PRIVATE_IP"
          echo "Resource Group: $RESOURCE_GROUP"





     
