name: VM State Change

on:
  workflow_dispatch:
    inputs:
      STATE:
        required: true
        type: choice
        options:
          - NONE
          - START
          - STOP
          - RESTART

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login to ACR
        id: aacr
        run: |
          # Your JSON data
          json_data='{"name": "zs-oyo-temp-vm","privateIp": "10.73.100.4","resourceGroup": "Oyo-migration-RG"}'

          echo $json_data
  
          echo "::set-output name=json_data::$json_data"
      - run: |
          extracted_json=$(echo "${{ steps.process_json.outputs.json_data }}")
          name=$(echo "$extracted_json" | jq -r '.name')
          privateIp=$(echo "$extracted_json" | jq -r '.privateIp')
          resourceGroup=$(echo "$extracted_json" | jq -r '.resourceGroup')

          echo "Name: $name"
          echo "Private IP: $privateIp"
          echo "Resource Group: $resourceGroup"






     
