name: test workflow

on:
  workflow_dispatch:
    inputs:
      PRODUCT_JIRA_TICKETS:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          ref: test
      - run: python test.py
      - name: Step that might fail
        run: |
          echo "This is a step that might fail"
          exit 1  # Simulating failure
        continue-on-error: true
      - uses: actions/checkout@master
        with:
          repository: shubhankitbansal/StrategyPattern
          token: ${{ secrets.SECRET_TOKEN }}
          path: ./StrategyPattern_TEMP
          submodules: recursive
      - run: |
          mkdir StrategyPattern
          cp -r StrategyPattern_TEMP/src/. ./StrategyPattern
          ls
          rm -r StrategyPattern_TEMP
      - uses: actions/checkout@master
        with:
          repository: shubhankitbansal/ObserverPattern
          token: ${{ secrets.SECRET_TOKEN }}
          path: ./ObserverPattern_TEMP
          submodules: recursive
