name: test workflow

on:
  workflow_dispatch:
    inputs:
      PRODUCT_JIRA_TICKETS:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          ref: test
      - run: python test.py
      - uses: actions/checkout@master
        with:
          repository: shubhankitbansal/StrategyPattern
          token: ${{ secrets.SECRET_TOKEN }}
          path: ./StrategyPattern
          submodules: recursive
      - uses: actions/checkout@master
        with:
          repository: shubhankitbansal/ObserverPattern
          token: ${{ secrets.SECRET_TOKEN }}
          path: ./ObserverPattern
          submodules: recursive
      - run: |
          pwd
          ls -la
          cd StrategyPattern
          ls -la
          python new_python_script.py
          pwd
          cd ../ObserverPattern
          ls -la
          pwd
