name: test workflow

on:
  workflow_dispatch:
    inputs:
      PRODUCT_JIRA_TICKETS:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          ref: test
      - run: python test.py
      - uses: actions/checkout@master
        with:
          name: shubhankitbansal/StrategyPattern
      - run: |
          ls
          python new_python_script.py
